[package]
name = "gpkg-usgs-lookup"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
gdal = "0.18.0"
quick-xml = "0.37.4"
reqwest = "0.12.15"
tempfile = "3.19.1"
tokio = {version = "1.44.1", features = ["macros", "rt-multi-thread"]}
 
